#需要替换intanceid 实例的具体名字
#需要替换#ETCDROOTPASSWORD# etcd管理员的密码

apiVersion: v1
kind: Service
metadata:
  name: sb-#BSIUID#-etcd
spec:
  ports:
  - name: etcd-client-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    servicebroker: #BSIUID#-etcd

---

#Route to client
apiVersion: v1
kind: Route
metadata:
  name: sb-#BSIUID#-etcd
spec:
  host: sb-#BSIUID#-etcd.app.dataos.io
  port:
    targetPort: etcd-client-port
  to:
    kind: Service
    name: sb-#BSIUID#-etcd

---



apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-#BSIUID#-etcd1
spec:
  replicas: 1
  selector:
    servicebroker_etcd_node: #BSIUID#-etcd1
  template:
    metadata:
      labels:
        servicebroker_etcd_node: #BSIUID#-etcd1
        servicebroker: #BSIUID#-etcd
    spec:
      containers:
      - command:
        - bash 
        - /usr/bin/etcd-join.sh
        - http://sb-#BSIUID#-etcd.app.dataos.io:80
        - etcd1
        - http://sb-#BSIUID#-etcd1:2380
        - sb-#BSIUID#-etcd
        - #ETCDROOTPASSWORD#
        image: 172.30.188.59:5000/#BSINAMESPACE#/etcd-openshift-orchestration:latest
        imagePullPolicy: Always
        name: etcd1
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /usr/bin/cluster_status.sh
            - #ETCDROOTPASSWORD#
            - http://sb-#BSIUID#-etcd0:2380
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sb-#BSIUID#-etcd1
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    servicebroker_etcd_node: #BSIUID#-etcd1

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-#BSIUID#-etcd2
spec:
  replicas: 1
  selector:
    servicebroker_etcd_node: #BSIUID#-etcd2
  template:
    metadata:
      labels:
        servicebroker_etcd_node: #BSIUID#-etcd2
        servicebroker: #BSIUID#-etcd
    spec:
      containers:
      - command:
        - bash 
        - /usr/bin/etcd-join.sh
        - http://sb-#BSIUID#-etcd.app.dataos.io:80
        - etcd2
        - http://sb-#BSIUID#-etcd2:2380
        - sb-#BSIUID#-etcd
        - #ETCDROOTPASSWORD#
        image: 172.30.188.59:5000/#BSINAMESPACE#/etcd-openshift-orchestration:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /usr/bin/cluster_status.sh
            - #ETCDROOTPASSWORD#
            - http://sb-#BSIUID#-etcd0:2380
        name: etcd3
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sb-#BSIUID#-etcd2
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    servicebroker_etcd_node: #BSIUID#-etcd2

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-#BSIUID#-etcd3
spec:
  replicas: 1
  selector:
    servicebroker_etcd_node: #BSIUID#-etcd3
  template:
    metadata:
      labels:
        servicebroker_etcd_node: #BSIUID#-etcd3
        servicebroker: #BSIUID#-etcd
    spec:
      containers:
      - command:
        - bash 
        - /usr/bin/etcd-join.sh
        - http://sb-#BSIUID#-etcd.app.dataos.io:80
        - etcd3
        - http://sb-#BSIUID#-etcd3:2380
        - sb-#BSIUID#-etcd
        - #ETCDROOTPASSWORD#
        image: 172.30.188.59:5000/#BSINAMESPACE#/etcd-openshift-orchestration:latest
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /usr/bin/cluster_status.sh
            - #ETCDROOTPASSWORD#
            - http://sb-#BSIUID#-etcd0:2380
        imagePullPolicy: Always
        name: etcd3
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sb-#BSIUID#-etcd3
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    servicebroker_etcd_node: #BSIUID#-etcd3

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-#BSIUID#-etcd0
spec:
  replicas: 1
  selector:
    servicebroker_etcd_node: #BSIUID#-etcd0
  template:
    metadata:
      labels:
        servicebroker_etcd_node: #BSIUID#-etcd0
        servicebroker: #BSIUID#-etcd
    spec:
      containers:
      - command:
        - bash
        - /usr/bin/etcd-init.sh
        - #ETCDROOTPASSWORD#
        - http://sb-#BSIUID#-etcd0:2380
        - http://sb-#BSIUID#-etcd.app.dataos.io:80
        - sb-#BSIUID#-etcd
        - #ETCDUSERPASSWORD#
        - etcd0
        image: 172.30.188.59:5000/#BSINAMESPACE#/etcd-openshift-orchestration:latest
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /usr/bin/cluster_status.sh
            - #ETCDROOTPASSWORD#
            - http://sb-#BSIUID#-etcd0:2380
        imagePullPolicy: Always
        name: etcd0
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sb-#BSIUID#-etcd0
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    servicebroker_etcd_node: #BSIUID#-etcd0

