apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-etcd3
spec:
  replicas: 1
  selector:
    servicebroker_etcd_node: instanceid-etcd3
  template:
    metadata:
      labels:
        servicebroker_etcd_node: instanceid-etcd3
        servicebroker: instanceid-etcd
    spec:
      containers:
      - command:
        - etcd-join.sh
        - http://sb-instanceid-etcd.app.asiainfodata.com:80
        - etcd3
        - http://sb-instanceid-etcd3:2380
        image: 172.30.40.148:5000/datafoundry-servicebroker/etcd-openshift-orchestration:latest
        imagePullPolicy: IfNotPresent
        name: etcd3
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sb-instanceid-etcd3
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    servicebroker_etcd_node: instanceid-etcd3

